SELECT
    BU.BU_NAME,
    DHA.CREATION_DATE,
    TRUNC(DHA.CREATION_DATE) AS CREATION_DATE2,
    DHA.ORDERED_DATE,
    DHA.ORDER_NUMBER,
    DST_H.DISPLAY_NAME AS ORDER_STATUS,
    DHA.CUSTOMER_PO_NUMBER,
    HZP.PARTY_NAME AS CUSTOMER_NAME,
    FLVHT.MEANING AS ORDER_TYPE,
    DHEB.ATTRIBUTE_CHAR1 AS INPUT_BY,
    DLA.LINE_NUMBER,
    ESIB.ITEM_NUMBER AS ITEM_CODE,
    ESIT.DESCRIPTION AS ITEM_DESCRIPTION,
    DLA.ORDERED_QTY AS QUANTITY,
    DLA.ORDERED_UOM AS UOM,
    DFL.REQUEST_SHIP_DATE,
    DFL.ACTUAL_SHIP_DATE,
    DST_L.DISPLAY_NAME AS LINE_STATUS,
    IOU.ORGANIZATION_NAME AS IO_NAME
FROM
    DOO_HEADERS_ALL DHA
    JOIN DOO_LINES_ALL DLA ON DHA.HEADER_ID = DLA.HEADER_ID
    JOIN DOO_FULFILL_LINES_ALL DFL ON DLA.LINE_ID = DFL.LINE_ID
    JOIN DOO_HEADERS_EFF_B DHEB ON DHA.HEADER_ID = DHEB.HEADER_ID AND DHEB.CONTEXT_CODE = 'Global'
    LEFT JOIN EGP_SYSTEM_ITEMS_B ESIB ON DFL.INVENTORY_ITEM_ID = ESIB.INVENTORY_ITEM_ID AND DFL.INVENTORY_ORGANIZATION_ID = ESIB.ORGANIZATION_ID
    LEFT JOIN EGP_SYSTEM_ITEMS_TL ESIT ON ESIB.INVENTORY_ITEM_ID = ESIT.INVENTORY_ITEM_ID AND ESIB.ORGANIZATION_ID = ESIT.ORGANIZATION_ID AND ESIT.LANGUAGE = USERENV('LANG')
    LEFT JOIN INV_ORGANIZATION_DEFINITIONS_V IOU ON DFL.FULFILL_ORG_ID = IOU.ORGANIZATION_ID
    LEFT JOIN FUN_ALL_BUSINESS_UNITS_V BU ON DHA.ORG_ID = BU.BU_ID
    LEFT JOIN HZ_PARTIES HZP ON DHA.SOLD_TO_PARTY_ID = HZP.PARTY_ID
    LEFT JOIN HZ_CUST_ACCOUNTS HCA ON HZP.PARTY_ID = HCA.CUST_ACCOUNT_ID
    LEFT JOIN DOO_STATUSES_B DSB_H ON DHA.STATUS_CODE = DSB_H.STATUS_CODE
    LEFT JOIN DOO_STATUSES_TL DST_H ON DSB_H.STATUS_ID = DST_H.STATUS_ID AND DST_H.LANGUAGE = USERENV('LANG')
    LEFT JOIN DOO_STATUSES_B DSB_L ON DFL.STATUS_CODE = DSB_L.STATUS_CODE
    LEFT JOIN DOO_STATUSES_TL DST_L ON DSB_L.STATUS_ID = DST_L.STATUS_ID AND DST_L.LANGUAGE = USERENV('LANG')
    LEFT JOIN FND_LOOKUP_VALUES_VL FLVHT ON DHA.ORDER_TYPE_CODE = FLVHT.LOOKUP_CODE AND FLVHT.LOOKUP_TYPE = 'ORA_DOO_ORDER_TYPES' AND FLVHT.VIEW_APPLICATION_ID = 0
WHERE DHA.STATUS_CODE <> 'DOO_REFERENCE'
    AND DHA.ORDERED_DATE BETWEEN '__START_DATE__' AND '__END_DATE__'
    AND DST_L.STATUS_NAME NOT IN ('Cancelled', 'Closed')
ORDER BY
--    BU.BU_NAME ASC NULLS LAST,
    DHA.ORDER_NUMBER DESC NULLS LAST,
    DHA.CREATION_DATE ASC NULLS LAST,
    DLA.LINE_NUMBER
