SELECT
    IPS.PICK_SLIP_NUMBER
    , CASE 
        WHEN UPPER(IPS.STATUS) LIKE '%PRINT%' OR IPS.STATUS = 'Y' THEN 'PRINTED' 
        ELSE 'NOT PRINTED' 
      END AS IS_PRINTED
    , CASE 
        WHEN UPPER(IPS.STATUS) LIKE '%PRINT%' OR IPS.STATUS = 'Y' THEN IPS.LAST_UPDATE_DATE 
        ELSE NULL 
      END AS PRINT_DATE
    , IOD.ORGANIZATION_NAME AS INVENTORY_ORGANIZATION_NAME
    , IOD.ORGANIZATION_CODE AS INVENTORY_ORGANIZATION_CODE
    , LISTAGG(DISTINCT CASE WHEN ITOH.HEADER_ID IS NOT NULL THEN ITOH.HEADER_NUMBER END, ', ') WITHIN GROUP (ORDER BY ITOH.HEADER_NUMBER) AS TO_ORDER_NUMBERS
    , LISTAGG(DISTINCT CASE WHEN ITOH.HEADER_NUMBER IS NULL AND DH.ORDER_NUMBER IS NOT NULL THEN DH.ORDER_NUMBER END, ', ') WITHIN GROUP (ORDER BY DH.ORDER_NUMBER) AS SO_ORDER_NUMBERS
FROM
    INV_PICK_SLIP_NUMBERS IPS
JOIN
    WSH_DELIVERY_DETAILS WDD ON IPS.PICK_SLIP_BATCH_ID = WDD.BATCH_ID
LEFT JOIN
    INV_TRANSFER_ORDER_HEADERS ITOH ON WDD.SOURCE_HEADER_ID = ITOH.HEADER_ID
JOIN
    INV_ORGANIZATION_DEFINITIONS_V IOD ON WDD.ORGANIZATION_ID = IOD.ORGANIZATION_ID
JOIN
    DOO_FULFILL_LINES_ALL DFL ON WDD.SOURCE_SHIPMENT_ID = DFL.FULFILL_LINE_ID
JOIN
    DOO_HEADERS_ALL DH ON DFL.HEADER_ID = DH.HEADER_ID
WHERE
    IPS.LAST_UPDATE_DATE BETWEEN '__START_DATE__' AND '__END_DATE__'
GROUP BY
    IPS.PICK_SLIP_NUMBER
    , IPS.STATUS
    , IPS.LAST_UPDATE_DATE
    , IOD.ORGANIZATION_NAME
    , IOD.ORGANIZATION_CODE
ORDER BY
    IPS.PICK_SLIP_NUMBER
