SELECT DISTINCT
    RCV.TRANSACTION_ID
    , TO_CHAR(RCV.TRANSACTION_DATE, 'YYYY-MM-DD HH24:MI:SS') AS TRANSACTION_DATE
    , POH.SEGMENT1 AS PO_NUMBER
    , RSH.RECEIPT_NUM
    , ESIB.ITEM_NUMBER
    , RSL.ITEM_DESCRIPTION
    , RCV.QUANTITY
    , RCV.UOM_CODE AS UNIT_OF_MEASURE
    , HZP.PARTY_NAME AS VENDOR_NAME
    , PSSA.VENDOR_SITE_CODE
    , IOP.ORGANIZATION_CODE AS INV_ORG_CODE
    , HR_ORG.NAME AS INV_ORG_NAME
    , FABU.BU_NAME AS BUSINESS_UNIT_NAME
FROM
    RCV_TRANSACTIONS RCV
    JOIN
    	RCV_SHIPMENT_HEADERS RSH 
        ON RCV.SHIPMENT_HEADER_ID = RSH.SHIPMENT_HEADER_ID
    JOIN 
    	RCV_SHIPMENT_LINES RSL 
        ON RCV.SHIPMENT_LINE_ID = RSL.SHIPMENT_LINE_ID
    JOIN 
    	PO_HEADERS_ALL POH 
        ON RCV.PO_HEADER_ID = POH.PO_HEADER_ID
    JOIN 
    	POZ_SUPPLIERS POS 
        ON RCV.VENDOR_ID = POS.VENDOR_ID
    JOIN 
    	HZ_PARTIES HZP 
        ON POS.PARTY_ID = HZP.PARTY_ID
    LEFT JOIN 
    	POZ_SUPPLIER_SITES_ALL_M PSSA 
        ON RCV.VENDOR_SITE_ID = PSSA.VENDOR_SITE_ID
    LEFT JOIN 
    	EGP_SYSTEM_ITEMS_B ESIB 
        ON RSL.ITEM_ID = ESIB.INVENTORY_ITEM_ID 
        AND RCV.ORGANIZATION_ID = ESIB.ORGANIZATION_ID
    LEFT JOIN 
    	INV_ORG_PARAMETERS_V IOP 
        ON RCV.ORGANIZATION_ID = IOP.ORGANIZATION_ID
    LEFT JOIN 
    	HR_ALL_ORGANIZATION_UNITS_F_VL HR_ORG 
        ON RCV.ORGANIZATION_ID = HR_ORG.ORGANIZATION_ID
    LEFT JOIN 
    	FUN_ALL_BUSINESS_UNITS_V FABU 
        ON IOP.BUSINESS_UNIT_ID = FABU.BU_ID
WHERE
    RCV.TRANSACTION_TYPE = 'RETURN TO VENDOR'
    AND RCV.TRANSACTION_DATE BETWEEN '__START_DATE__' AND '__END_DATE__'
ORDER BY
    RCV.TRANSACTION_DATE DESC
    , POH.SEGMENT1
