SELECT
    iop.ORGANIZATION_NAME AS "Org Name",
    wo.WORK_ORDER_NUMBER AS "Work Order Name",
    wd.WORK_DEFINITION_NAME_ID AS "Process Name",
    parent_item.ITEM_NUMBER AS "Item",
    wo.PLANNED_START_QUANTITY AS "Planned Quantity",
    wo.COMPLETED_QUANTITY AS "Actual Quantity",
    wo.UOM_CODE AS "UOM",
    TO_CHAR(wo.CREATION_DATE, 'YYYY-MM-DD') AS "Date",
    TO_CHAR(wo.PLANNED_START_DATE, 'YYYY-MM-DD') AS "Start Date",
    TO_CHAR(wo.RELEASED_DATE, 'YYYY-MM-DD') AS "Release Date",
    TO_CHAR(wo.ACTUAL_COMPLETION_DATE, 'YYYY-MM-DD') AS "Actual Completion Date",
    TO_CHAR(wo.CLOSED_DATE, 'YYYY-MM-DD') AS "Closed Date",
    status.WO_STATUS_NAME AS "Status",
    LISTAGG(
        txn."Transaction Date" || '|' || txn."Transaction Type",
        ';'
    ) WITHIN GROUP (ORDER BY txn."Transaction Date") AS "Transaction History"
FROM WIE_WORK_ORDERS_B wo
INNER JOIN INV_ORGANIZATION_DEFINITIONS_V iop ON wo.ORGANIZATION_ID = iop.ORGANIZATION_ID
LEFT JOIN WIS_WORK_DEFINITIONS wd ON wo.WORK_DEFINITION_ID = wd.WORK_DEFINITION_ID
INNER JOIN WIE_WO_STATUSES_VL status ON wo.WORK_ORDER_STATUS_ID = status.WO_STATUS_ID
INNER JOIN EGP_SYSTEM_ITEMS_B parent_item ON wo.INVENTORY_ITEM_ID = parent_item.INVENTORY_ITEM_ID AND wo.ORGANIZATION_ID = parent_item.ORGANIZATION_ID
INNER JOIN (
    SELECT WORK_ORDER_ID
    FROM (
        SELECT 
            imt.TRANSACTION_SOURCE_ID AS WORK_ORDER_ID,
            imt.TRANSACTION_DATE,
            tt.TRANSACTION_TYPE_NAME
        FROM INV_MATERIAL_TXNS imt
        INNER JOIN INV_TRANSACTION_TYPES_VL tt ON imt.TRANSACTION_TYPE_ID = tt.TRANSACTION_TYPE_ID
        WHERE imt.TRANSACTION_SOURCE_TYPE_ID = 5
        AND (tt.TRANSACTION_TYPE_NAME LIKE '%Material Issue%' OR tt.TRANSACTION_TYPE_NAME LIKE '%Product Completion%')
        AND imt.TRANSACTION_DATE BETWEEN TO_DATE('2026-05-01', 'YYYY-MM-DD') AND TO_DATE('2026-05-31', 'YYYY-MM-DD')
    )
    GROUP BY WORK_ORDER_ID
    HAVING MIN(CASE WHEN TRANSACTION_TYPE_NAME LIKE '%Product Completion%' THEN TRUNC(TRANSACTION_DATE) END) < 
           MIN(CASE WHEN TRANSACTION_TYPE_NAME LIKE '%Material Issue%' THEN TRUNC(TRANSACTION_DATE) END)
) anomaly ON wo.WORK_ORDER_ID = anomaly.WORK_ORDER_ID
INNER JOIN (
    SELECT 
        WORK_ORDER_ID,
        TO_CHAR(TRANSACTION_DATE, 'YYYY-MM-DD HH24:MI:SS') AS "Transaction Date",
        TRANSACTION_TYPE_NAME AS "Transaction Type",
        ROW_NUMBER() OVER (PARTITION BY WORK_ORDER_ID, TRANSACTION_TYPE_NAME ORDER BY TRANSACTION_DATE) as rn
    FROM (
        SELECT 
            imt.TRANSACTION_SOURCE_ID AS WORK_ORDER_ID,
            imt.TRANSACTION_DATE,
            tt.TRANSACTION_TYPE_NAME
        FROM INV_MATERIAL_TXNS imt
        INNER JOIN INV_TRANSACTION_TYPES_VL tt ON imt.TRANSACTION_TYPE_ID = tt.TRANSACTION_TYPE_ID
        WHERE imt.TRANSACTION_SOURCE_TYPE_ID = 5
        AND (tt.TRANSACTION_TYPE_NAME LIKE '%Material Issue%' OR tt.TRANSACTION_TYPE_NAME LIKE '%Product Completion%')
        AND imt.TRANSACTION_DATE BETWEEN TO_DATE('2026-05-01', 'YYYY-MM-DD') AND TO_DATE('2026-05-31', 'YYYY-MM-DD')
    )
) txn ON wo.WORK_ORDER_ID = txn.WORK_ORDER_ID AND txn.rn = 1
GROUP BY 
    iop.ORGANIZATION_NAME,
    wo.WORK_ORDER_NUMBER,
    wd.WORK_DEFINITION_NAME_ID,
    parent_item.ITEM_NUMBER,
    wo.PLANNED_START_QUANTITY,
    wo.COMPLETED_QUANTITY,
    wo.UOM_CODE,
    wo.CREATION_DATE,
    wo.PLANNED_START_DATE,
    wo.RELEASED_DATE,
    wo.ACTUAL_COMPLETION_DATE,
    wo.CLOSED_DATE,
    status.WO_STATUS_NAME
ORDER BY wo.WORK_ORDER_NUMBER;
