SELECT
    iop.ORGANIZATION_NAME AS org_name
    , wo.WORK_ORDER_NUMBER AS work_order_name
    , wd.WORK_DEFINITION_NAME_ID AS process_name
    , parent_item.ITEM_NUMBER AS item
    , wo.PLANNED_START_QUANTITY AS planned_quantity
    , wo.COMPLETED_QUANTITY AS actual_quantity
    , wo.UOM_CODE AS uom
    , TO_CHAR(wo.CREATION_DATE, 'YYYY-MM-DD') AS creation_date
    , TO_CHAR(wo.PLANNED_START_DATE, 'YYYY-MM-DD') AS start_date
    , TO_CHAR(wo.RELEASED_DATE, 'YYYY-MM-DD') AS release_date
    , TO_CHAR(wo.ACTUAL_COMPLETION_DATE, 'YYYY-MM-DD') AS actual_completion_date
    , TO_CHAR(wo.CLOSED_DATE, 'YYYY-MM-DD') AS closed_date
    , status.WO_STATUS_NAME AS status
    , LISTAGG(
        txn.transaction_date || '|' || txn.transaction_type,
        ';'
    ) WITHIN GROUP (ORDER BY txn.transaction_date) AS transaction_history
FROM WIE_WORK_ORDERS_B wo
INNER JOIN INV_ORGANIZATION_DEFINITIONS_V iop ON wo.ORGANIZATION_ID = iop.ORGANIZATION_ID
LEFT JOIN WIS_WORK_DEFINITIONS wd ON wo.WORK_DEFINITION_ID = wd.WORK_DEFINITION_ID
INNER JOIN WIE_WO_STATUSES_VL status ON wo.WORK_ORDER_STATUS_ID = status.WO_STATUS_ID
INNER JOIN EGP_SYSTEM_ITEMS_B parent_item ON wo.INVENTORY_ITEM_ID = parent_item.INVENTORY_ITEM_ID AND wo.ORGANIZATION_ID = parent_item.ORGANIZATION_ID
INNER JOIN (
    SELECT WORK_ORDER_ID
    FROM (
        SELECT 
            imt.TRANSACTION_SOURCE_ID AS WORK_ORDER_ID,
            imt.TRANSACTION_DATE,
            tt.TRANSACTION_TYPE_NAME
        FROM INV_MATERIAL_TXNS imt
        INNER JOIN INV_TRANSACTION_TYPES_VL tt ON imt.TRANSACTION_TYPE_ID = tt.TRANSACTION_TYPE_ID
        WHERE imt.TRANSACTION_SOURCE_TYPE_ID = 5
        AND (tt.TRANSACTION_TYPE_NAME LIKE '%Material Issue%' OR tt.TRANSACTION_TYPE_NAME LIKE '%Product Completion%')
        AND imt.TRANSACTION_DATE BETWEEN '__START_DATE__' AND '__END_DATE__'
    )
    GROUP BY WORK_ORDER_ID
    HAVING MIN(CASE WHEN TRANSACTION_TYPE_NAME LIKE '%Product Completion%' THEN TRUNC(TRANSACTION_DATE) END) < 
           MIN(CASE WHEN TRANSACTION_TYPE_NAME LIKE '%Material Issue%' THEN TRUNC(TRANSACTION_DATE) END)
) anomaly ON wo.WORK_ORDER_ID = anomaly.WORK_ORDER_ID
INNER JOIN (
    SELECT 
        WORK_ORDER_ID,
        TO_CHAR(TRANSACTION_DATE, 'YYYY-MM-DD HH24:MI:SS') AS transaction_date,
        TRANSACTION_TYPE_NAME AS transaction_type,
        ROW_NUMBER() OVER (PARTITION BY WORK_ORDER_ID, TRANSACTION_TYPE_NAME ORDER BY TRANSACTION_DATE) as rn
    FROM (
        SELECT 
            imt.TRANSACTION_SOURCE_ID AS WORK_ORDER_ID,
            imt.TRANSACTION_DATE,
            tt.TRANSACTION_TYPE_NAME
        FROM INV_MATERIAL_TXNS imt
        INNER JOIN INV_TRANSACTION_TYPES_VL tt ON imt.TRANSACTION_TYPE_ID = tt.TRANSACTION_TYPE_ID
        WHERE imt.TRANSACTION_SOURCE_TYPE_ID = 5
        AND (tt.TRANSACTION_TYPE_NAME LIKE '%Material Issue%' OR tt.TRANSACTION_TYPE_NAME LIKE '%Product Completion%')
        AND imt.TRANSACTION_DATE BETWEEN '__START_DATE__' AND '__END_DATE__'
    )
) txn ON wo.WORK_ORDER_ID = txn.WORK_ORDER_ID AND txn.rn = 1
GROUP BY 
    iop.ORGANIZATION_NAME
    , wo.WORK_ORDER_NUMBER
    , wd.WORK_DEFINITION_NAME_ID
    , parent_item.ITEM_NUMBER
    , wo.PLANNED_START_QUANTITY
    , wo.COMPLETED_QUANTITY
    , wo.UOM_CODE
    , wo.CREATION_DATE
    , wo.PLANNED_START_DATE
    , wo.RELEASED_DATE
    , wo.ACTUAL_COMPLETION_DATE
    , wo.CLOSED_DATE
    , status.WO_STATUS_NAME
__DYNAMIC_FILTERS__
ORDER BY 
    wo.WORK_ORDER_NUMBER
